
/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Friday, May 22, 2020 at 9:01:06 AM
   By task:     Import Data Wizard
   
   Source file: C:\Data\NBA\CSV\miscellaneous_stats_2011.csv
   Server:      Local
   
   Output data: WORK.MISCELLANEOUS_STATS_2011_0000
   Server:      Local
   -------------------------------------------------------------------- */

%macro miscstats(in,out,season);

DATA temp;
    LENGTH
        Rk                 8
        Team             $ 23
        Age                8
        W                  8
        L                  8
        PW                 8
        PL                 8
        MOV                8
        SOS                8
        SRS                8
        ORtg               8
        DRtg               8
        NRtg               8
        Pace               8
        FTr                8
        _3PAr              8
        TS_                8
        eFG_               8
        TOV_               8
        ORB_               8
        FT_FGA             8
        eFG__0001          8
        TOV__0001          8
        DRB_               8
        FT_FGA_0001        8
        Arena            $ 26
        Attend_            8
        Attend__G          8 ;
    LABEL
        _3PAr            = "3PAr"
        TS_              = "TS%"
        eFG_             = "eFG%"
        TOV_             = "TOV%"
        ORB_             = "ORB%"
        FT_FGA           = "FT/FGA"
        eFG__0001        = "eFG%"
        TOV__0001        = "TOV%"
        DRB_             = "DRB%"
        FT_FGA_0001      = "FT/FGA"
        Attend_          = "Attend."
        Attend__G        = "Attend./G" ;
    FORMAT
        Rk               BEST2.
        Team             $CHAR23.
        Age              BEST4.
        W                BEST2.
        L                BEST2.
        PW               BEST2.
        PL               BEST2.
        MOV              BEST5.
        SOS              BEST5.
        SRS              BEST5.
        ORtg             BEST5.
        DRtg             BEST5.
        NRtg             BEST4.
        Pace             BEST4.
        FTr              BEST4.
        _3PAr            BEST4.
        TS_              BEST4.
        eFG_             BEST4.
        TOV_             BEST4.
        ORB_             BEST4.
        FT_FGA           BEST4.
        eFG__0001        BEST4.
        TOV__0001        BEST4.
        DRB_             BEST4.
        FT_FGA_0001      BEST4.
        Arena            $CHAR26.
        Attend_          BEST6.
        Attend__G        BEST5. ;
    INFORMAT
        Rk               BEST2.
        Team             $CHAR23.
        Age              BEST4.
        W                BEST2.
        L                BEST2.
        PW               BEST2.
        PL               BEST2.
        MOV              BEST5.
        SOS              BEST5.
        SRS              BEST5.
        ORtg             BEST5.
        DRtg             BEST5.
        NRtg             BEST4.
        Pace             BEST4.
        FTr              BEST4.
        _3PAr            BEST4.
        TS_              BEST4.
        eFG_             BEST4.
        TOV_             BEST4.
        ORB_             BEST4.
        FT_FGA           BEST4.
        eFG__0001        BEST4.
        TOV__0001        BEST4.
        DRB_             BEST4.
        FT_FGA_0001      BEST4.
        Arena            $CHAR26.
        Attend_          BEST6.
        Attend__G        BEST5. ;
    INFILE "C:\Data\NBA\CSV\&in"
        LRECL=32767
        FIRSTOBS=3
        ENCODING="WLATIN1"
        DLM='2c'x
        MISSOVER
        DSD ;
    INPUT
        Rk               : ?? BEST2.
        Team             : $CHAR23.
        Age              : ?? COMMA4.
        W                : ?? BEST2.
        L                : ?? BEST2.
        PW               : ?? BEST2.
        PL               : ?? BEST2.
        MOV              : ?? COMMA5.
        SOS              : ?? COMMA5.
        SRS              : ?? COMMA5.
        ORtg             : ?? COMMA5.
        DRtg             : ?? COMMA5.
        NRtg             : ?? COMMA4.
        Pace             : ?? COMMA4.
        FTr              : ?? COMMA4.
        _3PAr            : ?? COMMA4.
        TS_              : ?? COMMA4.
        eFG_             : ?? COMMA4.
        TOV_             : ?? COMMA4.
        ORB_             : ?? COMMA4.
        FT_FGA           : ?? COMMA4.
        eFG__0001        : ?? COMMA4.
        TOV__0001        : ?? COMMA4.
        DRB_             : ?? COMMA4.
        FT_FGA_0001      : ?? COMMA4.
        Arena            : $CHAR26.
        Attend_          : ?? BEST6.
        Attend__G        : ?? BEST5. ;
RUN;

data temp2;
   set temp (rename=(TS_=TSP eFG_=eFGP TOV_=TOVP ORB_=ORBP FT_FGA=FTFGA
                                              eFG__0001=oeFGP TOV__0001=oTOVP DRB_=DRBP FT_FGA_0001=oFTFGA
                                              Attend__G=Attend team=team0));
   if index(team0,'*') then Playoff=1; else Playoff=0;
   Team=compress(team0,'*');
   drop team0 Arena Attend_ rk;
run;

data temp3;
   format WP 4.3;
   set temp2;
   WP=W/(W+L);
run;

data nba.&out;
   retain Team Age W L WP Playoff PW PL;
   set temp3;
   Season=&season;
run;

%mend;
%miscstats(miscellaneous_stats_2011.csv,MiscStats2011,2011);
%miscstats(miscellaneous_stats_2012.csv,MiscStats2012,2012);
%miscstats(miscellaneous_stats_2013.csv,MiscStats2013,2013);
%miscstats(miscellaneous_stats_2014.csv,MiscStats2014,2014);
%miscstats(miscellaneous_stats_2015.csv,MiscStats2015,2015);
%miscstats(miscellaneous_stats_2016.csv,MiscStats2016,2016);
%miscstats(miscellaneous_stats_2017.csv,MiscStats2017,2017);
%miscstats(miscellaneous_stats_2018.csv,MiscStats2018,2018);
%miscstats(miscellaneous_stats_2019.csv,MiscStats2019,2019);
%miscstats(miscellaneous_stats_2020.csv,MiscStats2020,2020);

data MiscStats00;
   set nba.MiscStats20:;
run;
proc sort; by team season; run;

proc sql;
   create table work.MiscStats01 as
   select a.*,
          b.Teamcode
   from work.MiscStats00 a,
        nba.Teamcode b
   where a.team=b.team;
quit;
proc freq; table team*teamcode / list; run;

data nba.MiscStats;
   retain Season Team TeamCode;
   set work.MiscStats01;
run;
proc sort; by season teamcode; run;


