
/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Saturday, June 6, 2020 at 11:40:40 AM
   By task:     Import Data Wizard
   
   Source file: C:\Data\NCAAB\kaggle\cbb.csv
   Server:      Local
   
   Output data: WORK.CBB_0000
   Server:      Local
   -------------------------------------------------------------------- */

DATA WORK.CBB000;
    LENGTH
        TEAM             $ 22
        CONF             $ 4
        G                  8
        W                  8
        ADJOE              8
        ADJDE              8
        BARTHAG            8
        EFG_O              8
        EFG_D              8
        TOR                8
        TORD               8
        ORB                8
        DRB                8
        FTR                8
        FTRD               8
        '2P_O'n            8
        '2P_D'n            8
        '3P_O'n            8
        '3P_D'n            8
        ADJ_T              8
        WAB                8
        POSTSEASON       $ 9
        SEED             $ 2
        YEAR               8 ;
    FORMAT
        TEAM             $CHAR22.
        CONF             $CHAR4.
        G                BEST2.
        W                BEST2.
        ADJOE            BEST5.
        ADJDE            BEST5.
        BARTHAG          BEST6.
        EFG_O            BEST4.
        EFG_D            BEST4.
        TOR              BEST4.
        TORD             BEST4.
        ORB              BEST4.
        DRB              BEST4.
        FTR              BEST4.
        FTRD             BEST4.
        '2P_O'n          BEST4.
        '2P_D'n          BEST4.
        '3P_O'n          BEST4.
        '3P_D'n          BEST4.
        ADJ_T            BEST4.
        WAB              BEST5.
        POSTSEASON       $CHAR9.
        SEED             $CHAR2.
        YEAR             BEST4. ;
    INFORMAT
        TEAM             $CHAR22.
        CONF             $CHAR4.
        G                BEST2.
        W                BEST2.
        ADJOE            BEST5.
        ADJDE            BEST5.
        BARTHAG          BEST6.
        EFG_O            BEST4.
        EFG_D            BEST4.
        TOR              BEST4.
        TORD             BEST4.
        ORB              BEST4.
        DRB              BEST4.
        FTR              BEST4.
        FTRD             BEST4.
        '2P_O'n          BEST4.
        '2P_D'n          BEST4.
        '3P_O'n          BEST4.
        '3P_D'n          BEST4.
        ADJ_T            BEST4.
        WAB              BEST5.
        POSTSEASON       $CHAR9.
        SEED             $CHAR2.
        YEAR             BEST4. ;
    INFILE 'C:\Data\NCAAB\kaggle\cbb.csv'
        LRECL=32767
        FIRSTOBS=2
        ENCODING="WLATIN1"
        DLM='2c'x
        MISSOVER
        DSD ;
    INPUT
        TEAM             : $CHAR22.
        CONF             : $CHAR4.
        G                : ?? BEST2.
        W                : ?? BEST2.
        ADJOE            : ?? COMMA5.
        ADJDE            : ?? COMMA5.
        BARTHAG          : ?? COMMA6.
        EFG_O            : ?? COMMA4.
        EFG_D            : ?? COMMA4.
        TOR              : ?? COMMA4.
        TORD             : ?? COMMA4.
        ORB              : ?? COMMA4.
        DRB              : ?? COMMA4.
        FTR              : ?? COMMA4.
        FTRD             : ?? COMMA4.
        '2P_O'n          : ?? COMMA4.
        '2P_D'n          : ?? COMMA4.
        '3P_O'n          : ?? COMMA4.
        '3P_D'n          : ?? COMMA4.
        ADJ_T            : ?? COMMA4.
        WAB              : ?? COMMA5.
        POSTSEASON       : $CHAR9.
        SEED             : $CHAR2.
        YEAR             : ?? BEST4. ;
RUN;


data temp1;
   set work.cbb000 (rename=('2P_O'n=_2PO '2P_D'n=_2PD '3P_O'n=_3PO '3P_D'n=_3PD));
run;
data ncaab.cbb;
   set work.temp1 (rename=(seed=seed0));
   if seed0='NA' then seed0='17';
   seed=seed0+0;
   drop seed0;
run;
proc sort; by year seed; run;



